FROM debian:latest
RUN apt-get update
RUN apt-get -y install g++ libtool make automake libc-ares-dev libavformat-dev libavcodec-dev libresiprocate-1.11-dev libortp-dev libexpat1-dev libboost-regex1.62-dev libgsm1-dev libcurl4-openssl-dev libssl1.0-dev libcommoncpp2-dev
CMD ["/bin/bash"]

