FROM centos:latest
RUN yum -y localinstall https://rhel7.iuscommunity.org/ius-release.rpm
RUN yum-config-manager --add-repo=https://negativo17.org/repos/epel-multimedia.repo
RUN yum -y install gcc-c++ libtool make automake c-ares-devel ffmpeg-devel ortp-devel resiprocate-devel expat-devel boost-devel gsm-devel libcurl-devel openssl-devel commoncpp2-devel
CMD ["/bin/bash"]

